version: '3.9'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    restart: always
    environment:
      - MSSQL_SA_PASSWORD=hotels123*
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    networks:
      - backend

  api:
    restart: always
    image: hotels:1.0
    build:
      context: .
      dockerfile: hotels.api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Hotels=Server=mssql;Database=HotelsDB;TrustServerCertificate=True;User=sa;Password=hotels123*;
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - mssql
    networks:
      - backend

networks:
  backend:
    external: false

volumes:
  sqlvolume: